apps/users/urls.py
from django.urls import path
from .views import SignupView, SignupsuccessView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .views import (UserDetailView, UserUpdateView, UserListView,
                      change_password,LoginView,UserCreateView,logout_view,
                    UserDeleteView,add_edit_group,
                   RoleDetailView,RoleListView,GroupDeleteView, set_language )
from django.urls import reverse_lazy

app_name= 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name="signup"),
    path('signup_success/', SignupsuccessView.as_view(), name="signup_success"),
    
    path('set_language/<str:language>/', set_language, name="set_language"),
    
    path('users/', login_required(UserListView.as_view()), name="userlist"),
    path('users/detail/<int:pk>', login_required(UserDetailView.as_view()), name="userdetail"),
    path('users/create/', UserCreateView.as_view(), name="user_create_view"),
    path('users/update/<int:pk>/', login_required(UserUpdateView.as_view()), name="edituser"),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete_view'),
    path('users/change_password/<int:pk>/', login_required(change_password), name="change_password"),


    path('logout/', logout_view, name='logout'),

     ###### PASSWORD RESET ##############
    path('password_reset/' , auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name= "registration/password_reset_email.html",
        success_url = reverse_lazy('users:password_reset_done'),), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/' , auth_views.PasswordResetConfirmView.as_view(
                    template_name='registration/password_change_form.html',
                    success_url = reverse_lazy('users:password_reset_complete'), 
                ), 
                name='password_reset_confirm'),
    path('password_reset/complete/' , auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),


    ###### ROLES ##############
    path('grouplist/', login_required(RoleListView.as_view()), name="grouplist"),
    path("create_role/", add_edit_group, name="create_role"),
    path("edit_role/<int:pk>/", add_edit_group, name="edit_role"),

    path('role_detail/<int:pk>/', RoleDetailView.as_view(), name="role_detail"),
    path("delete_group/<int:pk>/", GroupDeleteView.as_view(), name="delete_group"),

]   

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('', include('home.urls')),  
    path('admin/', admin.site.urls),
    path('client/', include('apps.clients.urls')),
    path('event/', include('apps.events.urls')),
    path('prestataires/', include(('apps.prestataires.urls', 'prestataire'), namespace='prestataire')),
    path('service/', include('apps.services.urls')),
    path('wilaya/', include('apps.wilayas.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('services/', include('apps.services.urls')),
    path('reviews/', include('apps.reviews.urls')),

    

    # path('prestataire/login/', views.prestataire_login, name='prestataire_login')

] + debug_toolbar_urls()

home/urls.py
from django.urls import path
from .views import home_view, select_event_type, select_venue_type, get_communes
from apps.clients.views import client_login_view, client_register_view
from .views import index
from django.urls import path, include
# from apps.prestataires.views import prestataire_login_view, prestataire_register_view

urlpatterns = [
    path('', home_view, name='home'),
    path('select-event/', select_event_type, name='select_event_type'),
    path('select-venue/<str:event_type>/', select_venue_type, name='select_venue_type'),
    path('login/client/', client_login_view, name='client_login'),
    # path('login/prestataire/', prestataire_login_view, name='prestataire_login'),
    path('register/client/', client_register_view, name='client_register'),
    path('get_communes/', get_communes, name='get_communes'),
    path('index/', index, name='index'),
    path('prestataires/', include('apps.prestataires.urls')),
]

apps/users/models.py
# Create your models here.
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db.models.functions import Substr, Concat
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.db.models import  Q, OuterRef, Exists
from django.utils import timezone





class UserQueryset(models.QuerySet):
    pass

class UserManager(BaseUserManager):
    use_in_migrations = True
    def get_queryset(self):
        return UserQueryset(self.model, using=self._db)

    def _create_user(self, email, password,**extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        groups = extra_fields.pop('groups', None)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        if groups:
            user.groups.set(groups)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        extra_fields.setdefault("is_active", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)



class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class User(AbstractUser, TimestampedModel):
    """ first_name last_name email is_staff is_active date_joined """
    username    = None
    full_name   = models.GeneratedField(
        verbose_name=_("Nom et prenom"),
        expression=Concat('first_name', models.Value(' '), 'last_name'),
        output_field=models.CharField(max_length=100),
        db_persist=True
    )
    email       = models.EmailField(_('E-mail address'), unique=True)
    picture     = models.ImageField(upload_to='images/faces', null=True, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=255, blank=True)

    is_manager  = models.BooleanField(default=False)
    is_client = models.BooleanField(default=False)
    is_prestataire = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()


    
        

apps/users/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.edit import FormView
from django.views.generic import UpdateView, ListView, TemplateView,DetailView,DeleteView
from .models import User
from django.contrib.auth.models import  Permission , Group
from django.contrib.auth.decorators import  permission_required
from django.views import View
import json
from django_htmx.http import HttpResponseClientRedirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import (AuthenticationForm, UserCreationForm, UserEditionForm, 
ChangePasswordForm,AddGroupForm)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
import logging
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.utils.translation import gettext as _
from django.contrib.auth.views import LoginView as DjangoLoginView
from django.contrib.auth import login as auth_login
from django.utils import translation
from django.conf import settings
from .utils import get_permissions
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_not_required
from django_htmx.http import HttpResponseClientRedirect 


logger = logging.getLogger(__name__)


# -----------------------------LOGIN--LOGOUT----------------------------------------------------------


class LoginView(DjangoLoginView):
    template_name="accounts/login.html"
    form_class = AuthenticationForm
    
    @method_decorator(login_not_required)
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            if self.request.user.is_prestataire:
                return HttpResponseClientRedirect('prestataires:prestataire_dashboard') 
            return HttpResponseClientRedirect('users:userdetail', kwargs={'pk': self.request.user.pk})
        return super().dispatch(request, *args, **kwargs)
    
    def get_success_url(self):
        user = self.request.user 
        if not user:
            messages.error(self.request, _("Email ou mot de passe incorrect."))
            return "/"
        if user.is_prestataire:
            return HttpResponseClientRedirect('prestataires:prestataire_dashboard') 
        return reverse('users:userdetail', kwargs={'pk': user.pk})
    
    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.error(self.request, _("Email ou mot de passe incorrect."))
        print('form.errors>>>>>>>', form.errors)
        print("user count", User.objects.count())
        return self.render_to_response(self.get_context_data(form=form))
    
    def form_valid(self, form):
        """Security check complete. Log the user in."""
        auth_login(self.request, form.get_user())

        # user_language = self.request.user.language or "fr"
        # print('user_language>>>>>>>', user_language)
        # translation.activate(user_language)
        # response.set_cookie(settings.LANGUAGE_COOKIE_NAME, user_language)
        return self.get_success_url()



def set_language(request, language="fr"):
    lang_code = language
    translation.activate(lang_code)
    request.session[settings.LANGUAGE_SESSION_KEY] = lang_code
    request.user.language = lang_code
    request.user.save()
    
    response = HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, lang_code)
    return response

def logout_view(request):
    logout(request)
    return redirect('/')

# -----------------------------------USER VIEWS----------------------------------------------------

class UserCreateView(PermissionRequiredMixin, FormView):
    permission_required = 'users.add_user'
    template_name = "accounts/snippets/create_user.html"
    form_class = UserCreationForm

    def form_valid(self, form):
        new_user = form.save()
        messages.success(self.request, _("Account Created successfully"))
        print('new_user>>>>>> ID', new_user.pk)
        return HttpResponse(status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "closeModal": "kt_modal",
                        "refresh_table": None
                    })
                }) 
    def form_invalid(self, form):
        messages.error(self.request, form.errors )
        return self.render_to_response(self.get_context_data(form=form)) 


class UserUpdateView(PermissionRequiredMixin, View):
    permission_required = 'users.change_user'
    template_name = "accounts/snippets/create_user.html"

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs['pk'])
        form = UserEditionForm(request,instance=user)
        context = {"form": form, "user": user}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs['pk'])
        form = UserEditionForm(request,request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, _("Account Updated successfully") )
            return HttpResponse(status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "closeModal": "kt_modal",
                        "refresh_table" : None
                    })
                })   
        
        else:
            messages.error(request, form.errors )
            return render(request, self.template_name, {'form': form, 'user': user})

class UserDeleteView(PermissionRequiredMixin,DeleteView):
    permission_required='users.delete_user'
    model = User
    template_name = "buttons/delete.html"
    success_url = reverse_lazy("users:userlist")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.delete()
        messages.success(self.request, "User Supprimer avec Succés" )
        return HttpResponseRedirect(success_url)


class UserDetailView(DetailView):
    model = User
    context_object_name = "user"
    template_name= "accounts/user-detail.html"
    def get_context_data(self, *args,**kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context["user_permissions"] = self.get_object().user_permissions.all()
        print('user groups', self.object.groups.all())
        context["user_groups"] = self.object.groups.all()  
        context['page_title'] = self.object

        context['permissions']= get_permissions()
        # print('permssios ns>>>>>>>>>>', self.get_object().user_permissions.all())
        return context
    
    def post(self, request, *args, **kwargs):
        user = self.get_object()
        perms = request.POST.getlist('perms')
        permissions = Permission.objects.filter(id__in=perms)
        user.user_permissions.set(permissions)
        user.save()
        messages.success(request, _('Profile updated successfully') )
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    

class UserListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_user'
    template_name = 'accounts/user_list.html' 
    success_url = reverse_lazy('users:userlist')
    context_object_name= "users"
    
    def get_template_names(self) -> list[str]:
        if self.request.htmx:
            return "accounts/snippets/user_list_block.html"
        else :
            return 'accounts/user_list.html' 

    
    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context["permissions"] = Permission.objects.all()
        context["user_groups"] = Group.objects.all()
        context['page_title'] = "Users"
        
        return context 
        

@permission_required('users.change_user', raise_exception=True)
def change_password(request, pk):
    context= {}
    template_name="accounts/snippets/change_password.html"
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        user_form = ChangePasswordForm(request.POST ,instance=user)
        if user_form.is_valid():
            cd = user_form.cleaned_data
            password = cd['password']
            password2 = cd['password2']
            if password == password2:
                user.set_password(password)
                user.save()
                messages.success(request, _('Mot de passe modifié avec succès'))
                redirect_url = reverse("users:userlist")
                return HttpResponseClientRedirect(redirect_url)
            else:
                messages.error(request, _('Formulaire invalide'))
        else:
            messages.error(request, _('Formulaire invalide'))
            context["form"]=ChangePasswordForm(data=request.POST or None )
            return render(request, template_name="accounts/snippets/change_password.html", context=context)
    else:
        user_form = ChangePasswordForm()  
    context = {'form': user_form, 'user': user}
    return render(request, template_name, context)





#-----------------------------------------groupe--------------------------------------------------------


#### CREATE  |  #### EDIT
@permission_required(('auth.add_group','auth.change_group'), raise_exception=True)
def add_edit_group(request, pk=None):
    context = {}
    context['page_title'] = _("Roles")
    role=None
    if pk:
        role = get_object_or_404(Group.objects.prefetch_related('permissions'), pk=pk)
    form  =  AddGroupForm( instance=role,)
    if request.method == "POST":
        form  =  AddGroupForm(request.POST, instance=role)
        if form.is_valid():
            form.save()
            message = _("Role created successfully")
            messages.success(request, str(message) )
            return HttpResponse(
                status=204,
                headers={

apps/users/templates/accounts/login.html
{% load static widget_tweaks %}
<form 
	hx-post="{% url 'users:login' %}"
	hx-target="closest .modal-body"
	hx-swap="innerHTML"
>
	{% csrf_token %}

	{% include 'forms/form-block.html' %}

	<button type="submit" class="btn btn-primary w-100">Se connecter</button>
</form>

apps/users/templates/accounts/user-detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
{% load i18n %}
{% load l10n %}
  <title>Compte</title>
{% endblock %} 
  
  
  <div class="d-flex flex-column flex-column-fluid">
    <div id="kt_app_content" class="app-content flex-column-fluid">
        <div class="card mb-5 mb-xl-10">
          <div class="card-body pt-9 pb-0">
            <div class="d-flex flex-wrap flex-sm-nowrap mb-3">
              <div class="me-7 mb-4">
                <div
                  class="symbol symbol-100px symbol-lg-120px symbol-fixed position-relative"
                >
                  {% if user.logo %}
                  <img src="{{user.logo.url}}" alt="image" />
                  {% else %}
                  <span
                    class="symbol-label fs-2x fw-semibold text-primary bg-light-primary"
                    >{{ user.get_username|slice:1 }}</span
                  >
                  {% endif %}
                </div>
              </div>
              <div class="flex-grow-1">
                <div
                  class="d-flex justify-content-between align-items-start flex-wrap"
                >
                  <div class="d-flex flex-column">
                    <div class="d-flex align-items-center mb-2">
                      <a
                        href="#"
                        class="text-gray-900 text-hover-primary fs-2 fw-bold me-1"
                        
                        >{{ user.get_username}}</a
                      >
                      {% if user.is_staff %}
                      <a
                        href="#"
                        class="btn btn-sm btn-light-success fw-bold ms-2 fs-8 py-1 px-3"
                        data-bs-toggle="modal"
                        data-bs-target="#kt_modal_upgrade_plan"
                        >{% trans 'Default' %}</a
                      >
                      {% endif %} {% if user.is_active %}
                      <a
                        href="#"
                        class="btn btn-sm btn-light-success fw-bold ms-2 fs-8 py-1 px-3"
                        data-bs-toggle="modal"
                        data-bs-target="#kt_modal_upgrade_plan"
                        >{% trans 'Active' %}</a
                      >
                      {% endif %}
                    </div>
                    <div class="d-flex flex-wrap fw-semibold fs-6 mb-4 pe-2">
                      <a
                        href="#"
                        class="d-flex align-items-center text-gray-400 text-hover-primary me-5 mb-2"
                        >{{user.warehouse}}</a
                      >
                      <a
                        href="#"
                        class="d-flex align-items-center text-gray-700 text-hover-primary me-5 mb-2"
                        >{{user.get_full_name}}</a>
                    </div>
                  </div>
                </div>
                <div class="tab-content" id="myTabContent"></div>
              </div>
            </div>
            <ul
              class="nav nav-stretch nav-line-tabs nav-line-tabs-2x border-transparent fs-5 fw-bold"
            >
              <li class="nav-item mt-2" role="presentation">
                <a
                  class="nav-link text-active-primary pb-4 active"
                  data-bs-toggle="tab"
                  href="#kt_user_view_overview"
                  aria-selected="false"
                  role="tab"
                  tabindex="-1"
                  hx-swap="innerHTML"
                  hx-trigger="refresh_table from:body,click"
                  hx-target="#OverviewTable"
                  >{% trans 'Overview' %}</a
                >
              </li>
  
              <li class="nav-item mt-2" role="presentation">
                {% if perms.auth.view_permission %}
                <a
                class="nav-link text-active-primary pb-4"
                data-bs-toggle="tab"
                href="#kt_user_view_permissons"
                aria-selected="false"
                role="tab"
                tabindex="-1"              
                hx-swap="innerHTML"
                hx-trigger="refresh_table from:body,click"
                hx-target="#PermissionsTable"
                >
                {% trans 'Permissions' %}</a
                >
                {% endif %}
              </li>
            </ul>
          </div>
        </div>
        <div class="d-flex flex-column flex-lg-row">
          <div class="flex-lg-row-fluid">
            <div class="tab-content" id="myTabContent">
              <div class="tab-pane fade active show" id="kt_user_view_overview" role="tabpanel">
                
                
                    <div  class="card-body pt-0 table-responsive" id="OverviewTable">
                        <div class="card mb-5 mb-xl-10" id="kt_profile_details_view">
                            <div class="card-header cursor-pointer">
                                <div class="card-title m-0">
                                  <h3 class="fw-bold m-0">{% translate "Profile" %}</h3>
                                </div>
                              <div class="d-flex align-items-center gap-2 gap-lg-3">
                              
                              {% if perms.users.change_user %}   
                                <a
                                  href="#"
                                  class="btn btn-sm fw-bold btn-primary d-block"
                                  data-bs-toggle="modal" 
                                  data-bs-target="#kt_modal"
                                  data-bs-toggle="tooltip" 
                                  data-bs-placement="right"
                                  hx-get="{% url 'users:edituser' user.pk %}"
                                  hx-target="#kt_modal_content"
                                  hx-swap="innerHTML"
                                >Modifier</a
                                >
                              {% endif %}
                            </div>
                          </div>
  
                          <div class="card-body p-9">
                              <div class="row mb-7">
                                  <label class="col-lg-4 fw-semibold text-muted">Email</label>
                                  <div class="col-lg-8">
                                      <span class="fw-bold fs-6 text-gray-800">{{user.email}}</span>
                                  </div>
                            </div>
  
                            <div class="row mb-7">
                                <label class="col-lg-4 fw-semibold text-muted">Mot de passe</label>
                                <div class="col-lg-4 fv-row">
                                    <span class="fw-semibold text-gray-800 fs-6">*******</span>
                                </div>
                              
                                
                                <div class="col-lg-4 fv-row text-end">
                                {% if perms.users.change_user %}
                                    <a 
                                      href="#"
                                      data-bs-toggle="modal" 
                                      data-bs-target="#kt_modal"
                                      data-bs-toggle="tooltip" 
                                      data-bs-placement="right"
                                      hx-get="{% url 'users:change_password' user.pk %}"
                                      hx-target="#kt_modal_content"
                                      hx-swap="innerHTML"
                                    >
                                    <i class="fas fa-edit" style="font-size: 1.5em;"></i>
                                  </a>
                                {% endif %}
                            </div>
                            </div>
  
                              <div class="row mb-7">
                                  <label class="col-lg-4 fw-semibold text-muted">Role</label>
                                  <div class="col-lg-8 fv-row">
                                      <span class="fw-semibold text-gray-800 fs-6">
                                        {% if user_groups %}
                                        {% for group in user_groups %}
                                            {{ group.name }}
                                        {% endfor %}
                                    {% else %}
                                        -
                                    {% endif %}
                                      </span>
                                  </div>
                              </div>
  
                              <div class="row mb-7">
                                <label class="col-lg-4 fw-semibold text-muted" >actif</label>
                                  <div class="col-lg-8">
                                      <a
                                        href="#"
                                        class="fw-semibold fs-6 text-gray-800 text-hover-primary"
                                        >{{user.is_active}}</a >
                                  </div>
                              </div>
                          </div>
                        </div>
                  
                  
                </div>
              </div>
              <div class="tab-pane fade" id="kt_user_view_permissons" role="tabpanel">
                  <form class="form" action="{% url 'users:userdetail' user.pk %}" method="POST">
                      {% csrf_token %}
                      <input type="hidden" name="my_user" value="{{ user.pk }}">
                      <div class="card pt-4 mb-6 mb-xl-9">
                          <div class="card-header mt-6">
                              <div class="card-title flex-column">
                                  <h2 class="mb-1">{% translate 'Permission' %}</h2>
                              </div>
                              <div class="card-toolbar">
                                  <button type="submit" class="btn btn-light-primary btn-sm">
                                      {% translate 'Submit' %}
                                  </button>
                              </div>
                          </div>
                          <div class="card-body pt-0 pb-5">
                              <div class="table-responsive">
                                  <table class="table align-middle table-row-dashed fs-6 gy-5">
                                      <tbody class="text-gray-600 fw-semibold">
                                          {% for model, perms in permissions.items %}
                                              <tr>
                                                  <td class="text-gray-800 align-top pt-5" style="width: 200px;">
                                                      {{ model }}
                                                      <div class="form-check mt-2">
                                                          <input type="checkbox" class="form-check-input select-all" data-target="group-{{ forloop.counter }}">
                                                          <label class="form-check-label small">{% translate "Select All" %}</label>
                                                      </div>
                                                  </td>
                                                  <td>
                                                      <div class="d-flex flex-wrap gap-3 group-{{ forloop.counter }}">
                                                          {% for perm in perms %}
                                                              <label class="form-check form-check-sm form-check-custom form-check-solid me-4">
                                                                  <input class="form-check-input" type="checkbox" value="{{ perm.id|unlocalize }}" name="perms"
                                                                      {% if perm in user_permissions %}checked{% endif %}>
                                                                  <span class="form-check-label">{{ perm.name }}</span>
                                                              </label>
                                                          {% endfor %}
                                                      </div>
                                                  </td>
                                              </tr>
                                          {% endfor %}
                                      </tbody>
                                  </table>

                                  <div class="text-center pt-15">
                                      <div class="card-toolbar">
                                          <button type="submit" class="btn btn-light-primary btn-sm">
                                              {% translate 'Submit' %}
                                          </button>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </form>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
  {% endblock content %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        document.querySelectorAll(".select-all").forEach(function (checkbox) {
            checkbox.addEventListener("change", function () {
                const groupClass = this.dataset.target;
                const checkboxes = document.querySelectorAll("." + groupClass + " input[type='checkbox']");
                checkboxes.forEach(cb => cb.checked = this.checked);
            });
        });
    });
</script>